Object Storage changes
bcgov/nr-fom-api pull request #103
Opened 2021-07-23 19:46 UTC by maguiarr

Using following environment variables:

- OBJECT_STORAGE_URL
- OBJECT_STORAGE_ACCESS_ID
- OBJECT_STORAGE_SECRET
- INSTANCE_URL_PREFIX

Files can be stored and retrieved from Object Storage
Deleting file from Object Storage if there's one there already of the PUBLIC_NOTICE type. Just following what's been done for database logic

2021-07-23 23:15 UTC, basilv requested changes

2021-07-23 23:15 UTC, basilv commented on apps/api/src/app/modules/attachment/attachment.service.ts
> +    request.fileContents = Buffer.from('hello world', 'utf8');
This should be flagged with a todo comment to remove this once we remove fileContents. In fact, given that you are already not using the column, you could configure the entity to not map the column, and clean this code up.

2021-07-23 23:15 UTC, basilv commented on apps/api/src/app/modules/attachment/attachment.service.ts
> +    if(process.env.INSTANCE_URL_PREFIX) {
Should check if INSTANCE_URL_PREFIX is length 0 as well (undefined or length 0 means don't use it)

2021-07-23 23:15 UTC, basilv commented on apps/api/src/minio.ts
> +minioClient.listBuckets(function(err, buckets) {
Why are we doing this? Looks like it could be removed.

2021-07-23 23:15 UTC, basilv commented on package.json
> +    "@auth0/angular-jwt": "^5.0.2",
There's a lot of extra libraries as new dependencies - this doesn't look right. Should just be adding minio I believe.

2021-07-24 03:40 UTC, maguiarr commented on package.json
> +    "@auth0/angular-jwt": "^5.0.2",
All I did was to branch from release/FOM-12 and then run npm run install. I actually cloned the entire nr-fom-api. I found strange too that so many libraries were installed. Maybe you'll have the same result if you run npm run install.

2021-07-26 21:28 UTC, merged